include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - prefer_single_quotes
    - prefer_final_locals
    - always_declare_return_types
    - unawaited_futures
    - directives_ordering
    - only_throw_errors
    - throw_in_finally
    - unnecessary_await_in_return
    - use_named_constants
